name: "CD Pipeline"

on:
  workflow_run:
    workflows: ["Sample React CI Pipeline / Workflow"]  # Make sure this matches exactly
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
            node-version: '21'
            
      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
                
      - name: "List extracted files"
        run: ls -R build

      - name: "Extract artifact"
        run: unzip build.zip -d build

      - name: "Display index.html"
        run: cat build/index.html

