name: "Sample React CI Pipeline / Workflow"
on: 
    push:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: "setup nodejs"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "check node version"
              run: node -v
            
            - name: "Clone the reporetory"
              uses: actions/checkout@v4
            
            - name: "list directories"
              run: ls

            - name: "install dependencies"
              run: npm install

            - name: "list directories"
              run: ls
            
            - name: "Run lint"
              run: npm run lint

            - name: "Run test"
              run: npm test

            - name: "Run Build"
              run: npm run build

            - name: "Upload product ready-build files"
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: dist  

            - name: "Check build output"
              run: ls -R dist

 
              

